import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: "#1A1A1A",
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 16,
  },
  centeredWrap: {
    flex: 1,
    justifyContent: "center",
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    backgroundColor: "#1A1A1A",
  },
  boardContent: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    gap: 16,
    paddingHorizontal: 2,
    paddingVertical: 16,
    paddingTop: 6,
    paddingBottom: 28,
  },
  pickScreenContainer: {
    flex: 1,
  },
  homeHeaderRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 2,
  },
  homeGreeting: {
    fontSize: 18,
    color: "#8A8A8A",
    fontFamily: "InterMedium",
  },
  homeUserName: {
    fontSize: 34,
    lineHeight: 38,
    color: "#F8FAFC",
    fontFamily: "InterBold",
  },
  homeAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  homeAvatarFallback: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#1A2C45",
    alignItems: "center",
    justifyContent: "center",
  },
  homeAvatarFallbackText: {
    color: "#5BA0F2",
    fontSize: 20,
    fontFamily: "InterBold",
  },
  homeHeroCard: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    borderRadius: 18,
    backgroundColor: "#1D5CC8",
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 8,
  },
  homeHeroTitle: {
    color: "#EFF6FF",
    fontSize: 20,
    fontFamily: "InterBold",
  },
  homeHeroSubtitle: {
    color: "#DBEAFE",
    fontSize: 16,
    fontFamily: "InterMedium",
  },
  homeHeroActionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 6,
  },
  homeHeroActionButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  homeHeroActionButtonPrimary: {
    backgroundColor: "#E2E8F0",
    borderColor: "#E2E8F0",
  },
  homeHeroActionButtonSecondary: {
    backgroundColor: "transparent",
    borderColor: "rgba(255,255,255,0.35)",
  },
  homeHeroActionText: {
    fontSize: 16,
    fontFamily: "InterBold",
  },
  homeHeroActionTextPrimary: {
    color: "#1D4ED8",
  },
  homeHeroActionTextSecondary: {
    color: "#DBEAFE",
  },
  homeSectionTitle: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    color: "#8A8A8A",
    fontSize: 16,
    fontFamily: "InterBold",
    letterSpacing: 0.5,
  },
  homeFilterRow: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  homeRideList: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    gap: 10,
  },
  homeActiveRideCard: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#1E1E1E",
    borderRadius: 16,
    padding: 14,
    gap: 10,
  },
  homeEmptyStateCard: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#262626",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 22,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 2,
  },
  homeEmptyStateText: {
    color: "#C0C0C0",
    fontSize: 18,
    fontFamily: "InterMedium",
  },
  homeFilterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#1E1E1E",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  homeFilterChipActive: {
    borderColor: "#5BA0F2",
    backgroundColor: "#1A2C45",
  },
  homeFilterChipText: {
    color: "#B8B8B8",
    fontSize: 14,
    fontFamily: "InterMedium",
  },
  homeFilterChipTextActive: {
    color: "#DBEAFE",
    fontFamily: "InterBold",
  },
  homeFilterChipMuted: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#222222",
    paddingHorizontal: 14,
    paddingVertical: 8,
    opacity: 0.7,
  },
  homeFilterChipMutedText: {
    color: "#C0C0C0",
    fontSize: 14,
    fontFamily: "InterMedium",
  },
  homePricePill: {
    borderRadius: 999,
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  homePricePillText: {
    color: "#166534",
    fontSize: 12,
    fontFamily: "InterBold",
  },
  homeRequestButton: {
    borderRadius: 14,
    backgroundColor: "#276EF1",
    minWidth: 108,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  homeRequestButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontFamily: "InterBold",
  },
  title: {
    fontSize: 30,
    textAlign: "left",
    color: "#FFFFFF",
    fontFamily: "InterBold",
  },
  description: {
    fontSize: 16,
    lineHeight: 22,
    textAlign: "left",
    color: "#8A8A8A",
    fontFamily: "InterMedium",
  },
  card: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    gap: 16,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#262626",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 2,
  },
  signInCard: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 20,
    gap: 22,
  },
  signInHeader: {
    alignItems: "center",
    gap: 2,
  },
  signInBrand: {
    fontSize: 42,
    lineHeight: 46,
    color: "#FFFFFF",
    fontFamily: "InterBold",
    letterSpacing: -1.2,
  },
  signInSubBrand: {
    fontSize: 16,
    color: "#8A8A8A",
    fontFamily: "InterMedium",
  },
  signInHeadline: {
    fontSize: 17,
    lineHeight: 27,
    textAlign: "center",
    color: "#D0D0D0",
    fontFamily: "InterMedium",
    paddingHorizontal: 14,
  },
  signInMicrosoftButton: {
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: "#276EF1",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 16,
  },
  signInMicrosoftButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "InterBold",
  },
  signInMicrosoftIcon: {
    width: 18,
    height: 18,
    gap: 2,
  },
  signInMicrosoftRow: {
    flexDirection: "row",
    gap: 2,
  },
  signInMicrosoftTile: {
    width: 8,
    height: 8,
  },
  signInMicrosoftTileRed: {
    backgroundColor: "#F25022",
  },
  signInMicrosoftTileGreen: {
    backgroundColor: "#7FBA00",
  },
  signInMicrosoftTileBlue: {
    backgroundColor: "#00A4EF",
  },
  signInMicrosoftTileYellow: {
    backgroundColor: "#FFB900",
  },
  signInRestriction: {
    textAlign: "center",
    color: "#8A8A8A",
    fontSize: 14,
    fontFamily: "InterMedium",
  },
  signInDivider: {
    height: 1,
    backgroundColor: "#383838",
  },
  signInLegalText: {
    textAlign: "center",
    color: "#606060",
    fontSize: 12,
    lineHeight: 18,
    fontFamily: "InterMedium",
    paddingHorizontal: 18,
  },
  cameraWrap: {
    borderRadius: 14,
    overflow: "hidden",
  },
  camera: {
    width: "100%",
    aspectRatio: 3 / 4,
    minHeight: 280,
    maxHeight: 420,
    borderRadius: 14,
  },
  buttonRow: {
    gap: 12,
  },
  buttonBase: {
    borderRadius: 12,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  buttonPrimary: {
    backgroundColor: "#276EF1",
  },
  buttonSecondary: {
    backgroundColor: "#2A2A2A",
    borderWidth: 1,
    borderColor: "#444444",
  },
  buttonDanger: {
    backgroundColor: "#3F1D1D",
    borderWidth: 1,
    borderColor: "#7F1D1D",
  },
  buttonSuccess: {
    backgroundColor: "#14532D",
    borderWidth: 1,
    borderColor: "#166534",
  },
  buttonPressed: {
    opacity: 0.88,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 15,
    fontFamily: "InterMedium",
  },
  buttonTextSecondary: {
    color: "#F8FAFC",
  },
  buttonTextDanger: {
    color: "#FECACA",
  },
  input: {
    borderWidth: 1,
    borderColor: "#404040",
    backgroundColor: "#1E1E1E",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 15,
    color: "#F0F0F0",
    fontFamily: "InterMedium",
  },
  sectionLabel: {
    fontSize: 17,
    color: "#FFFFFF",
    fontFamily: "InterBold",
  },
  quickRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  vehicleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  vehicleChip: {
    borderWidth: 1,
    borderColor: "#404040",
    backgroundColor: "#1E1E1E",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  vehicleChipSelected: {
    borderColor: "#5BA0F2",
    backgroundColor: "#1A2C45",
  },
  vehicleChipText: {
    fontSize: 14,
    color: "#B8B8B8",
    fontWeight: "600",
    fontFamily: "InterMedium",
  },
  vehicleChipTextSelected: {
    color: "#DBEAFE",
  },
  postList: {
    gap: 10,
  },
  postItem: {
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#222222",
    borderRadius: 16,
    padding: 14,
    gap: 6,
  },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  postName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    fontFamily: "InterBold",
  },
  postMeta: {
    fontSize: 13,
    color: "#8A8A8A",
    fontFamily: "InterMedium",
  },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeOpen: {
    backgroundColor: "#052E16",
  },
  badgeFull: {
    backgroundColor: "#3F1D1D",
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  badgeTextOpen: {
    color: "#86EFAC",
  },
  badgeTextFull: {
    color: "#FCA5A5",
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 24,
    backgroundColor: "#276EF1",
    borderRadius: 999,
    minWidth: 84,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 5,
  },
  fabText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  profileTopRight: {
    alignSelf: "flex-end",
    alignItems: "center",
    gap: 4,
    marginBottom: 6,
  },
  profileAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#5BA0F2",
  },
  profileAvatarFallback: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#5BA0F2",
    backgroundColor: "#1A2C45",
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarFallbackText: {
    color: "#DBEAFE",
    fontWeight: "700",
    fontFamily: "InterMedium",
  },
  profileSignOut: {
    color: "#5BA0F2",
    fontSize: 12,
    fontWeight: "600",
    fontFamily: "InterMedium",
  },
  profileIdentityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profileIdentityTextWrap: {
    flex: 1,
    gap: 2,
  },
  profileHeroAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: "#5BA0F2",
  },
  profileHeroAvatarFallback: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: "#5BA0F2",
    backgroundColor: "#1A2C45",
    alignItems: "center",
    justifyContent: "center",
  },
  profileHeroAvatarFallbackText: {
    color: "#DBEAFE",
    fontWeight: "700",
    fontSize: 24,
    fontFamily: "InterMedium",
  },
  profileName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    fontFamily: "InterBold",
  },
  profileEmail: {
    fontSize: 14,
    color: "#8A8A8A",
    fontFamily: "InterMedium",
  },
  starRow: {
    flexDirection: "row",
    gap: 8,
  },
  starButton: {
    width: 42,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#404040",
    backgroundColor: "#1E1E1E",
    alignItems: "center",
    justifyContent: "center",
  },
  starButtonActive: {
    borderColor: "#5BA0F2",
    backgroundColor: "#1A2C45",
  },
  starText: {
    color: "#666666",
    fontSize: 20,
  },
  starTextActive: {
    color: "#5BA0F2",
  },
  feedbackTextArea: {
    minHeight: 96,
  },
  moderationMetricRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  moderationMetricCard: {
    flexGrow: 1,
    flexBasis: 150,
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#222222",
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  moderationMetricValue: {
    fontSize: 34,
    fontWeight: "700",
    color: "#FFFFFF",
    fontFamily: "InterBold",
  },
  moderationMetricLabel: {
    fontSize: 14,
    color: "#8A8A8A",
    fontFamily: "InterMedium",
  },
  moderationFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  moderationFilterButtonWrap: {
    flexGrow: 1,
    minWidth: 150,
  },
  moderationSelectedItem: {
    borderColor: "#5BA0F2",
    backgroundColor: "#1A2C45",
  },
  moderationQuote: {
    fontSize: 20,
    fontStyle: "italic",
    color: "#C0C0C0",
    lineHeight: 30,
    fontFamily: "InterMedium",
  },
  moderationActionFlex: {
    flex: 1,
  },
  moderationContextCard: {
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#1E1E1E",
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  moderationContextRouteChip: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#404040",
    backgroundColor: "#2A2A2A",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  moderationContextRouteText: {
    color: "#D0D0D0",
    fontSize: 13,
    fontFamily: "InterMedium",
  },
  sectionMarker: {
    fontSize: 12,
    fontFamily: "InterBold",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "#8A8A8A",
  } as const,
  moderationStatRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 6,
    paddingHorizontal: 2,
  },
  moderationStatValue: {
    fontSize: 15,
    fontFamily: "InterBold",
    color: "#FFFFFF",
  },
  moderationStatLabel: {
    fontSize: 14,
    fontFamily: "InterMedium",
    color: "#8A8A8A",
  },
  moderationStatSep: {
    fontSize: 15,
    fontFamily: "InterMedium",
    color: "#444444",
  },
  moderationContextRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    paddingVertical: 6,
  },
  moderationContextLabel: {
    color: "#8A8A8A",
    fontSize: 13,
    fontFamily: "InterMedium",
  },
  moderationContextValue: {
    color: "#FFFFFF",
    fontSize: 14,
    textAlign: "right",
    flexShrink: 1,
    fontFamily: "InterBold",
  },
  moderationContextDivider: {
    height: 1,
    backgroundColor: "#383838",
  },
  personRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  personAvatarSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#5BA0F2",
  },
  personAvatarFallbackSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#5BA0F2",
    backgroundColor: "#1A2C45",
    alignItems: "center",
    justifyContent: "center",
  },
  personAvatarFallbackTextSmall: {
    color: "#DBEAFE",
    fontWeight: "700",
    fontSize: 11,
    fontFamily: "InterMedium",
  },
  overlayBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  overlayCard: {
    backgroundColor: "#262626",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#383838",
    padding: 18,
    gap: 12,
  },
  overlayProfileAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: "#5BA0F2",
  },
  overlayProfileAvatarFallback: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: "#5BA0F2",
    backgroundColor: "#1A2C45",
    alignItems: "center",
    justifyContent: "center",
  },
  overlayProfileAvatarFallbackText: {
    color: "#DBEAFE",
    fontWeight: "700",
    fontSize: 28,
    fontFamily: "InterMedium",
  },
});

export const lightStyleOverrides = StyleSheet.create({
  screenContainer: { backgroundColor: "#F4F6FB" },
  loadingWrap: { backgroundColor: "#F4F6FB" },
  homeGreeting: { color: "#6B7280" },
  homeUserName: { color: "#111827" },
  homeHeroCard: { backgroundColor: "#1D5CC8" },
  homeHeroTitle: { color: "#EFF6FF" },
  homeHeroSubtitle: { color: "#DBEAFE" },
  homeSectionTitle: { color: "#6B7280" },
  homeActiveRideCard: { borderColor: "#E4E7EE", backgroundColor: "#FFFFFF" },
  homeFilterChip: { borderColor: "#D1D5DB", backgroundColor: "#FFFFFF" },
  homeFilterChipText: { color: "#374151" },
  homeFilterChipMuted: { borderColor: "#D1D5DB", backgroundColor: "#F8FAFC", opacity: 1 },
  homeFilterChipMutedText: { color: "#6B7280" },
  title: { color: "#111827" },
  description: { color: "#4B5563" },
  card: { borderColor: "#E4E7EE", backgroundColor: "#FFFFFF" },
  buttonPrimary: { backgroundColor: "#C30052" },
  buttonSecondary: { backgroundColor: "#FCE7F3", borderColor: "#F9A8D4" },
  buttonDanger: { backgroundColor: "#FEE2E2", borderColor: "#FECACA" },
  buttonTextSecondary: { color: "#9D174D" },
  buttonTextDanger: { color: "#B91C1C" },
  input: { borderColor: "#D6DCE7", backgroundColor: "#FAFBFF", color: "#111827" },
  sectionLabel: { color: "#111827" },
  vehicleChip: { borderColor: "#D6DCE7", backgroundColor: "#F8FAFC" },
  vehicleChipSelected: { borderColor: "#b50246", backgroundColor: "#FCE7F3" },
  vehicleChipText: { color: "#334155" },
  vehicleChipTextSelected: { color: "#9D174D" },
  postItem: { borderColor: "#E4E7EE", backgroundColor: "#FCFCFF" },
  postName: { color: "#111827" },
  postMeta: { color: "#334155" },
  badgeOpen: { backgroundColor: "#DCFCE7" },
  badgeFull: { backgroundColor: "#FEE2E2" },
  badgeTextOpen: { color: "#166534" },
  badgeTextFull: { color: "#B91C1C" },
  fab: { backgroundColor: "#b50246" },
  profileAvatar: { borderColor: "#F9A8D4" },
  profileAvatarFallback: { borderColor: "#F9A8D4", backgroundColor: "#FCE7F3" },
  profileAvatarFallbackText: { color: "#9D174D" },
  profileSignOut: { color: "#9D174D" },
  profileHeroAvatar: { borderColor: "#F9A8D4" },
  profileHeroAvatarFallback: { borderColor: "#F9A8D4", backgroundColor: "#FCE7F3" },
  profileHeroAvatarFallbackText: { color: "#9D174D" },
  profileName: { color: "#111827" },
  profileEmail: { color: "#4B5563" },
  starButton: { borderColor: "#D6DCE7", backgroundColor: "#F8FAFC" },
  starButtonActive: { borderColor: "#b50246", backgroundColor: "#FCE7F3" },
  starTextActive: { color: "#b50246" },
  moderationMetricCard: { borderColor: "#E4E7EE", backgroundColor: "#F8FAFC" },
  moderationMetricValue: { color: "#111827" },
  moderationMetricLabel: { color: "#4B5563" },
  moderationContextCard: { borderColor: "#E4E7EE", backgroundColor: "#F8FAFC" },
  moderationContextRouteChip: { borderColor: "#D6DCE7", backgroundColor: "#FFFFFF" },
  moderationContextRouteText: { color: "#334155" },
  moderationContextLabel: { color: "#64748B" },
  moderationContextValue: { color: "#111827" },
  moderationContextDivider: { backgroundColor: "#E2E8F0" },
  moderationSelectedItem: { borderColor: "#b50246", backgroundColor: "#FFF1F6" },
  moderationQuote: { color: "#475569" },
  personAvatarSmall: { borderColor: "#F9A8D4" },
  personAvatarFallbackSmall: { borderColor: "#F9A8D4", backgroundColor: "#FCE7F3" },
  personAvatarFallbackTextSmall: { color: "#9D174D" },
  overlayCard: { borderColor: "#E4E7EE", backgroundColor: "#FFFFFF" },
  overlayProfileAvatar: { borderColor: "#F9A8D4" },
  overlayProfileAvatarFallback: { borderColor: "#F9A8D4", backgroundColor: "#FCE7F3" },
  overlayProfileAvatarFallbackText: { color: "#9D174D" },
});


